// apps/ptg-react-app/src/app/auth/login/Login.tsx
/**
 * @since March 2022
 * @author Ankit patidar
 * @desc Reusable Login Component
 *
 */

import './Login.scss';
import { useState, useEffect } from 'react';
import React from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate } from 'react-router-dom';
import { authClass } from '../services/auth.service';
import ForgotPassword from '../forgotpassword/ForgotPassword';
import {
  PtgUiButton,
  PtgUiInput,
  PtgUiLoading,
  PtgUiAlert,
} from '@ptg-ui/react';
import msalInstance from '../msal';
import { acquireToken } from '../msal'; 

export interface PtgUiLoginProps {}

export function PtgUiLogin(props: PtgUiLoginProps) {

  const loginMsal = async ()=>{
     const loginRequest = {
          scopes: ["user.read","https://management.azure.com/user_impersonation"]
   };
   const response = await msalInstance.loginPopup(loginRequest);
   const [error, tokenResponse] = await acquireToken(loginRequest);
   console.log("Hello i'm in msal",tokenResponse)
   authClass.setToken(JSON.stringify(response));
    navigate('/calendar');
  }

  const { t } = useTranslation();
  const [user, setUser]: any = useState({
    isLoading: false,
    isAlert: false,
    email: '',
    password: '',
    error: null,
    disable: true,
  });

  const [formErr, setFormErr] = useState({
    email: false,
    password: false,
  });

  const navigate = useNavigate();

  const setState: any = (field: string, value: any) => {
    setUser((preState: any) => {
      return {
        ...preState,
        [field]: value,
      };
    });
  };

  const setErrState: any = (field: string, value: any) => {
    setFormErr((preState: any) => {
      return {
        ...preState,
        [field]: value,
      };
    });
  };

  const isDisabled: any = () => {
    setState(
      'disable',
      !(
        user.email.length > 0 &&
        user.password.length > 0 &&
        !formErr.email &&
        !formErr.password
      )
    );
  };
  //validate email and password
  const validate = (fieldName: string, value: any) => {
    let formErr = false;
    switch (fieldName) {
      case 'email':
        const regexEmail = /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/i;
        if (value === '' || value ? true : false !== regexEmail.test(value)) {
          if (!regexEmail.test(value)) {
            formErr = true;
          }
        }
        break;
      case 'password':
        if (value === '') {
          formErr = true;
        }
        break;
      default: {
      }
    }

    setErrState(fieldName, formErr);
  };

  //generic function for all input field
  const handleChange: any = (e: any) => {
    const { name, value } = e.target;
    validate(name, value);
    setUser((preState: any) => {
      return {
        ...preState,
        [name]: value,
      };
    });
  };

  const handleLogin = (event: any) => {
    event.preventDefault();
    setState('error', null);
    //console.log(error);
    setState('isLoading', true);
    authClass
      .login({
        identifier: user.email,
        password: user.password,
      })
      .then((response: any) => {
        setState('isLoading', false);
        if (response.statusCode && response.statusCode !== 200) {
          throw new Error('Function not implemented.');
        } else if (response.jwt !== '') {
          authClass.setToken(JSON.stringify(response));
          authClass.setRole(response.user.role.type);
          if (response.user.role.type.trim() == 'admin') {
            navigate('/admin-home');
          } else {
            navigate('/calendar');
          }
        }
      })
      .catch((error: any) => {
        setState('isAlert', true);
      });
  };

  //validate on focus out or blur input
  const handleBlur: any = (e: any) => {
    const { name } = e.target;
    setFormErr((preState: any) => {
      return {
        ...preState,
        [name]: true,
      };
    });
  };

  useEffect(() => {
    isDisabled();
  }, [user.email, user.password]);

  return (
    <React.Fragment>
      {user.isLoading && <PtgUiLoading />}
      <div className="login-wrapper container-fluid p-0 d-flex justify-content-center align-items-center">
        <div className="login-container">
          <div className="login-form-wrapper">
            <div className="form-group">
              {user.isAlert && <PtgUiAlert message={t('ERROR_MSG')} />}
            </div>
            <div className="form-group">
              <div className="login-logo text-center mb-3">
                <img
                  className=""
                  src="assets/logo.png"
                  alt={t('IMG_WebsiteLOGO')}
                />
              </div>
            </div>
            <form className="form-login">
              <div className="login-form">
                <div className="form-group mb-4 required">
                  <label
                    htmlFor="inputEmail"
                    aria-labelledby="inputEmail"
                    tabIndex={0}
                  >
                    {t('LABEL_EMAIL')}
                  </label>
                  <div className="userid input-group flex-nowrap">
                    <div className="input-group-prepend">
                      <i className="login-user-icon"></i>
                    </div>
                    <PtgUiInput
                      type="email"
                      id="inputEmail"
                      value={user.email}
                      onChange={handleChange}
                      className={`"w-100 form-control bg_0 ${
                        formErr.email === true ? 'border-danger' : ''
                      }`}
                      name="email"
                      placeholder={t('INPUT_PLACEHOLDER_EMAIL')}
                      onBlur={user.email === '' ? handleBlur : null}
                    />
                  </div>
                </div>
                <div className="form-group mb-4 required">
                  <label
                    htmlFor="inputPassword"
                    aria-labelledby="inputPassword"
                    tabIndex={0}
                  >
                    {t('LABEL_PASSWORD')}
                  </label>
                  <div className="forgot-password float-end" tabIndex={0}>
                    <ForgotPassword />
                  </div>
                  <div className="userid input-group flex-nowrap">
                    <div className="input-group-prepend">
                      <i className="login-password-icon"></i>
                    </div>
                    <PtgUiInput
                      type="password"
                      id="inputPassword"
                      onChange={handleChange}
                      value={user.password}
                      className={`"w-100 form-control bg_0 ${
                        formErr.password === true ? 'border-danger' : ''
                      }`}
                      name="password"
                      placeholder={t('INPUT_PLACEHOLDER_PASSWORD')}
                      onBlur={user.password === '' ? handleBlur : null}
                    />
                  </div>
                </div>
              </div>
              <div className="new_label text-center mb-3">
                <label tabIndex={0}>
                  {t('LABEL_INFO_MSG')}{' '}
                  <Link to="/signup" className="signup-btn">
                    {t('SIGN_UP')}
                  </Link>
                  .
                </label>
              </div>
              <PtgUiButton
                className="w-100"
                onClick={handleLogin}
                tabIndex={0}
                disabled={user.disable}
                data-testid="login"
                // accessKey="s"
              >
                {t('LOG_IN')}
              </PtgUiButton>
               <p className="text-center mx-3 mb-0">{t('OR')}</p>
               <PtgUiButton
                className="w-100"
                onClick={loginMsal}
                tabIndex={0}
                // accessKey="s"
              >
                {t('Msal')}
              </PtgUiButton>
            </form>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

export default PtgUiLogin;

// apps/ptg-angular-app/src/app/auth/login/login.component.ts
/* eslint-disable @nx/enforce-module-boundaries */
/* eslint-disable @typescript-eslint/no-empty-function */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable @nx/enforce-module-boundaries */

/**
 * @since March 2022
 * @author Bhanu Prakash Sharma
 * @Component ptg-ui-login;
 * @description This component for login
 **/

import { Component, OnDestroy, OnInit, TemplateRef } from '@angular/core';
import { User } from '@ptg-angular-app/auth/models/user.model';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { AuthService } from '@ptg-angular-app/auth/services/auth.service';
import { Router } from '@angular/router';
import { Subject, takeUntil } from 'rxjs';
import { BsModalService, BsModalRef } from 'ngx-bootstrap/modal';
import { resources } from '../../../resource/resource';

@Component({
  selector: 'ptg-ui-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss'],
})
export class LoginComponent implements OnInit, OnDestroy {
  loginForm!: FormGroup;
  submitted = false;
  user: User = new User();
  errorMessage!: string | null;
  loading = false;
  unsubscribe: Subject<any> = new Subject();
  modalRef?: BsModalRef;
  resources = resources;
  response: any;

  get f() {
    return this.loginForm.controls;
  }

  constructor(
    private formBuilder: FormBuilder,
    private auth: AuthService,
    private router: Router,
    private modalService: BsModalService
  ) {}

  ngOnInit(): void {
    this.loginForm = this.formBuilder.group({
      email: ['', [Validators.required, Validators.email]], //
      password: ['', [Validators.required]],
    });
  }

  // This method for login submit
  onLoginSubmit(): void {
    this.submitted = true;
    const payload = {
      identifier: this.loginForm.value.email,
      password: this.loginForm.value.password,
    };
    this.userLogin(payload);
  }

  // This method for login api call
  userLogin(payload: any) {
    this.loading = true;
    this.auth
      .logIn(payload)
      .pipe(takeUntil(this.unsubscribe))
      .subscribe({
        next: (res) => {
          // For response success
          console.log('11133', res);
          this.auth.setToken(JSON.stringify(res));
          this.loading = false;
          this.errorMessage = null;
          this.loginForm.reset();
          this.response = res;

          if (this.response.user?.role?.type == 'admin') {
            // console.log('11134', 'value');
            this.router.navigate(['/admin']);
          } else {
            this.router.navigate(['/']);
          }
        },
        error: (err) => {
          this.errorMessage = 'Invalid email or password';
          this.loading = false;
        },
        complete: () => {},
      });
  }

  // Method for close alert
  closeAlert(event: any): void {
    this.errorMessage = event;
  }

  // Method for show modal
  showModal(template: TemplateRef<any>) {
    this.modalRef = this.modalService?.show(template);
  }

  // Method for close modal
  isClosemodal() {
    this.modalRef?.hide();
  }

  socialLogin() {
    console.log('working');
  }

  ngOnDestroy(): void {
    this.unsubscribe.next(0);
    this.unsubscribe.complete();
  }
}

<!-- Loading -->
<ptg-ui-loading [loading]="loading"></ptg-ui-loading>
<!-- <header></header>
<h1 hidden>Login</h1> -->
<!-- Login wrapper Start -->
<div class="login-wrapper container-fluid p-0 d-flex justify-content-center align-items-center">
    <div class="login-container">
        <div class="login-form-wrapper">
            <div class="form-group">
                <!-- alert -->
                <ptg-ui-alert *ngIf="errorMessage" [type]="'danger'" [message]="errorMessage" [isDismissible]="true"
                    (closeAlert)="closeAlert($event)">
                </ptg-ui-alert>
            </div>
            <div class="form-group">
                <div class=" text-center mb-3">
                    <img src="/assets/yash-logo-new@2x.png" alt="log is basically use to show purpose" />
                </div>
            </div>
            <form class="form-login" [formGroup]="loginForm" (ngSubmit)="onLoginSubmit()">
                <div class="login-form">
                    <div class="form-group mb-4">
                        <label for="inputEmail" [innerHTML]="resources.LABEL_EMAIL"></label>
                        <div class="userid input-group flex-nowrap">
                            <div class="input-group-prepend">
                                <i class="login-user-icon"></i>
                            </div>
                            <!-- input -->
                            <ptg-ui-input class="w-100" formControlName="email" [id]="'inputEmail'" type="text"
                                className="form-control bg_0" aria_placeholder="email"
                                [placeholder]="resources.INPUT_PLACEHOLDER_EMAIL">
                            </ptg-ui-input>
                        </div>
                    </div>
                    <div class="form-group mb-4">
                        <label for="inputPassword" [innerHTML]="resources.LABEL_PASSWORD"></label>
                        <a (click)="showModal(template)" class="forgot-password float-end">
                            {{resources.FORGOT_PASSWORD}}?</a>
                        <div class="userid input-group flex-nowrap">
                            <div class="input-group-prepend">
                                <i class="login-password-icon"></i>
                            </div>
                            <!-- input -->
                            <ptg-ui-input class="w-100" [id]="'inputPassword'" type="password"
                                formControlName="password" className="form-control bg_0"
                                [placeholder]="resources.INPUT_PLACEHOLDER_PASSWORD" aria_placeholder="password">
                            </ptg-ui-input>
                        </div>
                    </div>
                    <div class="new_label text-center mb-3">
                        <label>{{resources.REGISTRATION_LABEL_INFO_MSG}}

                            <a class="signup-btn" [routerLink]="['../signup']">{{resources.SIGN_UP}}</a>.</label>
                    </div>
                    <!-- button -->
                    <ptg-ui-button tabindex="0" class="w-100" type="submit" btnStyleType="primary" id="btnSignin"
                        [isBlock]="true" [isDisable]="!loginForm.valid">
                        {{resources.SIGN_IN}}
                    </ptg-ui-button>
                    <!-- <span>Or login in using</span>
                    <ptg-ui-button tabindex="0" class="w-100" type="button" btnStyleType="primary" id="btnSocialSignin" [isBlock]="true" (click)="socialLogin()">
                        Sign in with Google
                    </ptg-ui-button> -->
                </div>
            </form>
        </div>
    </div>
</div>
<!-- Login wrapper End -->

<!-- Dialog for forgotpassword -->
<ng-template #template let-modal>
    <div class="modal-body app-orders p-0">
        <ptg-ui-forgotpassword [modalRef]="modalRef">
            <!-- button -->
            <ptg-ui-button (click)="isClosemodal()" class="" btnStyleType="secondary">
                Cancel
            </ptg-ui-button>
        </ptg-ui-forgotpassword>
    </div>
</ng-template>
