// apps/ptg-angular-app/src/app/dashboard/infinite-scroll/infinite-scroll.component.ts
import { HttpClient } from '@angular/common/http';
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'ptg-ui-infinite-scroll-component',
  templateUrl: './infinite-scroll.component.html',
  styleUrls: ['./infinite-scroll.component.scss'],
})
export class InfiniteScrollComponent implements OnInit{
    items: any =[];
    page  = 1;
    height  = "350px";
    hasData = false;
    showCode= false;

  htmlCode = `
  <ptg-infinite-scroll  [items]="items" [fetchData]="fetchDataFunction" 
                               [height]="height" [hasData]="hasData">
                <ul *ngIf="items && items.length > 0">
                    <li *ngFor="let i of items; let key= index">
                        <span>{{i.id}} &nbsp; </span>{{i.title}}
                    </li>
                </ul>
  </ptg-infinite-scroll>
 `;

  tsCode = `
  import { HttpClient } from '@angular/common/http';
  import { Component, OnInit } from '@angular/core';

  @Component({
    selector: 'ptg-ui-infinite-scroll-component',
    templateUrl: './infinite-scroll.component.html',
    styleUrls: ['./infinite-scroll.component.scss'],
  })
  export class InfiniteScrollComponent implements OnInit{
      items: any =[];
      page  = 1;
      height  = "350px";
      hasData = false;
      showCode= false;

      constructor(private httpClient: HttpClient) {}

      ngOnInit(){
        this.fetchDataFunction();
      }
    
       fetchDataFunction= async () => {
        try {
          const response = await fetch("https://jsonplaceholder.typicode.com/posts?_page=${this.page}&_limit=15");
          const data = await response.json();
          if(data && data.length > 0){
                if(data && data.length > 0){
                    this.items = [...this.items, ...data];
                    this.hasData = true;
                    this.page = this.page + 1;
                } else{
                    this.hasData = false;
                }
          } 
          
        } catch (error:any) {
          console.log(error);
        } 
      }
  `;

  constructor(private httpClient: HttpClient) {}

  ngOnInit(){
    this.fetchDataFunction();
  }

   fetchDataFunction= async () => {
    try {
      const response = await fetch(`https://jsonplaceholder.typicode.com/posts?_page=${this.page}&_limit=15`);
      const data = await response.json();
      if(data && data.length > 0){
            if(data && data.length > 0){
                this.items = [...this.items, ...data];
                this.hasData = true;
                this.page = this.page + 1;
            } else{
                this.hasData = false;
            }
      } 
      
    } catch (error:any) {
      console.log(error);
    } 
  }

}

<section class="infinite pt-2">
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">
          <h4 class="mb-3" [innerHTML]="'Infinite Scroll' | translate"></h4>
          <ptg-ui-toggle-code
            [htmlCode]="htmlCode"
            [tsCode]="tsCode"
          ></ptg-ui-toggle-code>
          <div class="mb-3">
            <ptg-infinite-scroll  [items]="items" [fetchData]="fetchDataFunction" 
                               [height]="height" [hasData]="hasData">
                <ul *ngIf="items && items.length > 0">
                    <li *ngFor="let i of items; let key= index">
                        <span>{{i.id}} &nbsp; </span>{{i.title}}
                    </li>
                </ul>
            </ptg-infinite-scroll>
          </div>
        </div>
    </div>
  </div>
</section>

// apps/ptg-react-app/src/app/examples/infinite-scroll/infinite-scroll.tsx
import React, { useState, useEffect } from 'react';
import { PtgInfiniteScroll } from '@ptg-ui/libs/ptg-ui-web-components-react/src';
import CodeIcon from '@mui/icons-material/Code';
import ShowCodeComponent from '../../common/showCode/showCodeComponent';


export default function InfiniteScroll() {
  const [items, setItems] = useState([] as any);
  const [page, setPage] = useState(1);
  const height = "350px";
  const [hasData,setHasData] = useState(false);
  const [showCode, setShowCode] = useState(false);

  const fetchDataFunction = async () => {
  
    try {
      const response = await fetch(`https://jsonplaceholder.typicode.com/posts?_page=${page}&_limit=15`);
      const data = await response.json();
      if(data && data.length > 0){
        setItems(data);
        setHasData(true);
      }
      else{
        setHasData(false);
      }
     
    } catch (error:any) {
      console.log(error);
    } 
  };

  useEffect(() => {
    fetchDataFunction();
  }, [page]);
  
  const componentCode = `
  import { PtgInfiniteScroll } from '@ptg-ui/libs/ptg-ui-web-components-react';
  const [items, setItems] = useState([] as any);
  const [page, setPage] = useState(1);
  const height = "350px";
  const [hasData,setHasData] = useState(false);
  const [showCode, setShowCode] = useState(false);

  const fetchDataFunction = async () => {
  
    try {
      const response = await fetch('https://jsonplaceholder.typicode.com/posts?_page=${page}&_limit=15');
      const data = await response.json();
      if(data && data.length > 0){
        setItems(data);
        setHasData(true);
      }
      else{
        setHasData(false);
      }
     
    } catch (error:any) {
      console.log(error);
    } 
  };

  useEffect(() => {
    fetchDataFunction();
  }, [page]);
  `;

  const htmlCode = `
 <PtgInfiniteScroll items={items} fetchData={fetchDataFunction} setPage={setPage} height={height} hasData={hasData}>
 `;

  return (
    <div className="row">
    <div className="col-md-11 mb-3">
      <h3 className="font-weight-bold">Infinite Scroll</h3>
    </div>
    <div className="col-1">
      <CodeIcon
        onClick={() => setShowCode((prev) => !prev)}
        fontSize="medium"
        className="show-code-icon"
      ></CodeIcon>
    </div>
    {showCode && (
      <ShowCodeComponent componentCode={componentCode} htmlCode={htmlCode} />
    )}
    <div className="col-md-12">
   <PtgInfiniteScroll items={items} fetchData={fetchDataFunction} setPage={setPage} height={height} hasData={hasData}>
    {
        items && items.length > 0?
        <ul>
            {items.map((i)=>(
                <li key={i.id}>
                    <span>{i.id} &nbsp;</span>
                    {i.title}
                </li>
            ))}
        </ul>
        :<></>
    }
   </PtgInfiniteScroll>
   </div>
   </div>
   );
}
