// apps/ptg-ui-web-comp-react/src/app/pages/Input.tsx
import { PtgInput } from '@ptg-ui/ptg-ui-web-components-react';

function Input() {
  return (
    <div className="input container">
      <h3 className="title-align">Input</h3>
      <div className="row">
        <PtgInput
          type="text"
          inputId="name"
          label="Name"
          placeholder="Enter Name"
          name="abc"
          value="abc"
        ></PtgInput>
      </div>
    </div>
  );
}

export default Input;

// apps/ptg-ui-web-comp-angular/src/app/componets/input/input.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'ptg-ui-input',
  templateUrl: './input.component.html',
  styleUrls: ['./input.component.css']
})
export class InputComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="input container">
    <h3 class="title-align">Input</h3>    
    <div class="row">
      <ptg-input
        type="text"
        inputId="name"
        label="Name"
        placeholder="Enter Name"
        name="abc"
        value="abc"
      ></ptg-input>
    </div>
  </div>
