// apps/ptg-ui-web-comp-angular/src/app/componets/loading/loading.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'ptg-ui-loading',
  templateUrl: './loading.component.html',
  styleUrls: ['./loading.component.css']
})
export class LoadingComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="container">
    <h3 class="title-align">Loading</h3>
    <div class="row">
      <ptg-spinner appearance="primary"></ptg-spinner>
      <ptg-spinner appearance="secondary"></ptg-spinner>
      <ptg-spinner appearance="info"></ptg-spinner>
      <ptg-spinner appearance="warning"></ptg-spinner>
      <ptg-spinner appearance="danger"></ptg-spinner>
      <ptg-spinner appearance="success"></ptg-spinner>
    </div>
  </div>

// apps/web-comp-react/src/app/pages/Loading.jsx
import { PtgSpinner } from '@ptg-ui/web-components-react';

function Loading() {
  return (
    <div class="container">
      <h3 className="title-align">Loading</h3>
      <div class="row">
        <PtgSpinner appearance="primary"></PtgSpinner>
        <PtgSpinner appearance="secondary"></PtgSpinner>
        <PtgSpinner appearance="info"></PtgSpinner>
        <PtgSpinner appearance="warning"></PtgSpinner>
        <PtgSpinner appearance="danger"></PtgSpinner>
        <PtgSpinner appearance="success"></PtgSpinner>
      </div>
    </div>
  );
}
export default Loading;
