// apps/ptg-ui-web-comp-angular/src/app/componets/textarea/textarea.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'ptg-ui-textarea',
  templateUrl: './textarea.component.html',
  styleUrls: ['./textarea.component.css']
})
export class TextareaComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<h3>Text Area Component</h3>
 <ptg-textarea placeholder="Enter Your Comments Here...."></ptg-textarea>
        <ptg-textarea
          placeholder="Enter Your Comments Here...."
          appearance="danger"
        ></ptg-textarea>

// apps/web-comp-react/src/app/pages/Textarea.jsx
import React from 'react';
import { PtgTextarea } from '@ptg-ui/web-components-react';

function Textarea() {
  return (
    <div class="container">
      <h3 className="title-align">Textarea</h3>
      <div class="row">
        <PtgTextarea placeholder="Enter Your Comments Here...."></PtgTextarea>
        <PtgTextarea
          placeholder="Enter Your Comments Here...."
          appearance="danger"
        ></PtgTextarea>
      </div>
    </div>
  );
}
export default Textarea;
