// apps/ptg-react-app/src/app/common/reset/Reset.tsx
/**
 * @since March 2022
 * @author Anmol Mathur
 * @desc Reset Component
 * 
*/
import {PtgUiButton,PtgUiInput} from '@ptg-ui/react';
import { useTranslation } from 'react-i18next';
import { useState, useEffect } from 'react';
import { Modal } from 'react-bootstrap';
import './Reset.scss';

export default function Reset() {
  const { t } = useTranslation();
  const [show, setShow] = useState(false);
  const handleClose = () => setShow(false);
  const handleShow = () => setShow(true);
  const [resetDisable, setResetDisable] = useState(true);

  const oldPassword = useFormInput('', '');
  const newPassword = useFormInput('', '');
  const confirmPassword = useFormInput('', newPassword.value);

  useEffect(() => {
    validateForm();
  }, [oldPassword.value, newPassword.value, confirmPassword.value]);

  const validateForm = () => {
    let validFlag = true;
    if (
      oldPassword.value !== '' &&
      newPassword.value !== '' &&
      confirmPassword.value !== '' &&
      newPassword.value === confirmPassword.value
    ) {
      validFlag = false;
    }
    setResetDisable(validFlag);
  };

  return (
    <div>
      <a onClick={handleShow}>{t('RESET_PASSWORD_TEXT')}</a>
      <Modal show={show}>
        <div className="reset-wrapper container-fluid p-0 d-flex justify-content-center align-items-center">
          <div className="reset-container">
            <div className="reset-form-wrapper">
              <div className="form-group">
                {/* <ptg-ui-alert *ngIf="errorMessage" [type]="'danger'" [message]="errorMessage" [isDismissible]='true'
                        (closeAlert)="closeAlert($event)">
                    </ptg-ui-alert> */}
              </div>
              <div className="form-group">
                <div className="text-center mb-3">
                  <h3>{t('RESET_PASSWORD_TEXT')}</h3>
                </div>
              </div>
              <form className="form-forgot">
                <div className="forgot-form">
                  <div className="form-group required mb-2">
                    <label htmlFor="inputOldPass">
                      {t('OLD_PASSWORD_TEXT')}
                    </label>
                    <PtgUiInput
                      {...oldPassword}
                      className={`w-100 form-control bg_0 ${
                        oldPassword.error === 'true' ? 'border-danger' : ''
                      }`}
                      type="password"
                      placeholder={t('OLD_PASSWORD_PLACEHOLDER')}
                    />
                  </div>
                  <div className="form-group required mb-2">
                    <label htmlFor="inputNewPass">
                      {t('NEW_PASSWORD_TEXT')}
                    </label>
                    <PtgUiInput
                      {...newPassword}
                      className={`w-100 form-control bg_0 ${
                        newPassword.error === 'true' ? 'border-danger' : ''
                      }`}
                      name="newPassword"
                      // id='inputNewPass'
                      type="password"
                      placeholder={t('NEW_PASSWORD_PLACEHOLDER')}
                    />
                  </div>
                  <div className="form-group required mb-2">
                    <label htmlFor="inputconfirmPass">
                      {t('CONFIRM_PASSWORD_LABEL')}
                    </label>
                    <PtgUiInput
                      {...confirmPassword}
                      className={`w-100 form-control bg_0 ${
                        confirmPassword.error === 'true' ? 'border-danger' : ''
                      }`}
                      name="confirmPassword"
                      // id='inputconfirmPass'
                      type="password"
                      placeholder={t('CONFIRM_PASSWORD_PLACEHOLDERE')}
                    />
                  </div>
                  <div className="row">
                    <div className="col-7">
                      <PtgUiButton
                        className=""
                        type="submit"
                        disabled={resetDisable}
                      >
                        {t('RESET_PASSWORD_TEXT')}
                      </PtgUiButton>
                    </div>
                    <div className="col-5">
                      <PtgUiButton variant="secondary" onClick={handleClose}>
                        {t('CANCEL')}
                      </PtgUiButton>
                    </div>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </Modal>
    </div>
  );
}
const useFormInput = (initialValue: any, passCheck: any) => {
  const [value, setValue] = useState(initialValue);
  const [error, setError] = useState('false');
  const handleChange = (event: any) => {
    const { name, value } = event.target;
    setValue(value);
    if (value === '') setError('true');
    else setError('false');
    if (name === 'confirmPassword' && value !== passCheck) {
      setError('true');
    }
  };
  return {
    value,
    onChange: handleChange,
    error,
  };
};

// apps/ptg-angular-app/src/app/common/reset/reset.component.ts
/* eslint-disable @nx/enforce-module-boundaries */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable @angular-eslint/no-empty-lifecycle-method */
/* eslint-disable @typescript-eslint/no-empty-function */

/**
 * @since March 2022
 * @author Bhanu Prakash Sharma
 * @Component ptg-ui-reset;
 * @description This component for reset password
 **/

import { Component, Input, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { PTGToastsService } from '@ptg-ui/angular/toasts';
import { ConfirmPasswordValidator } from '../utils/validators';
import { BsModalRef } from 'ngx-bootstrap/modal';
import { resources } from '../../../resource/resource';

@Component({
  selector: 'ptg-ui-reset',
  templateUrl: './reset.component.html',
  styleUrls: ['./reset.component.scss'],
})
export class ResetComponent implements OnInit {
  @Input() modalRef?: BsModalRef;
  resetForm!: FormGroup;
  loading = false;
  errorMessage = null;
  resources = resources;

  get f() {
    return this.resetForm.controls;
  }

  constructor(
    private formBuilder: FormBuilder,
    private toastr: PTGToastsService
  ) {}

  ngOnInit(): void {
    this.resetForm = this.formBuilder.group(
      {
        oldPassword: ['', [Validators.required]],
        newPassword: ['', [Validators.required]],
        confirmPassword: ['', [Validators.required]],
      },
      {
        validator: ConfirmPasswordValidator('newPassword', 'confirmPassword'),
      }
    );
  }

  // This method for Reset form submit
  onResetSubmit() {
    this.toastr.showSuccess('', '');
    this.modalRef?.hide();
    this.resetForm.reset();
  }

  closeAlert(event: any) {}
}

<!-- Loading -->
<ptg-ui-loading [loading]="loading"></ptg-ui-loading>

<!-- reset wrapper Start -->
<div class="reset-wrapper container-fluid p-0 d-flex justify-content-center align-items-center">
    <div class="reset-container">
        <div class="reset-form-wrapper">
            <div class="form-group">
                <!-- alert -->
                <ptg-ui-alert *ngIf="errorMessage" [type]="'danger'" [message]="errorMessage" [isDismissible]='true'
                    (closeAlert)="closeAlert($event)">
                </ptg-ui-alert>
            </div>
            <div class="form-group">
                <div class="text-center mb-3">
                    <h3 [innerHTML]="resources.RESET_PASSWORD_TEXT"></h3>
                </div>
            </div>
            <form class="form-forgot" [formGroup]="resetForm" (ngSubmit)="onResetSubmit()">
                <div class="forgot-form">
                    <div class="form-group required mb-2">
                        <label for="inputOldPass" [innerHTML]="resources.OLD_PASSWORD_TEXT"></label>
                        <!-- input -->
                        <ptg-ui-input class="w-100" formControlName='oldPassword' id='inputOldPass' type="password"
                            className="form-control bg_0" [placeholder]="resources.OLD_PASSWORD_PLACEHOLDER">
                        </ptg-ui-input>
                    </div>
                    <div class="form-group required mb-2">
                        <label for="inputNewPass" [innerHTML]="resources.NEW_PASSWORD_TEXT"></label>
                        <!-- input -->
                        <ptg-ui-input class="w-100" formControlName='newPassword' id='inputNewPass' type="password"
                            className="form-control bg_0" [placeholder]="resources.NEW_PASSWORD_PLACEHOLDER">
                        </ptg-ui-input>
                    </div>
                    <div class="form-group required mb-2">
                        <label for="inputconfirmPass" [innerHTML]="resources.CONFIRM_PASSWORD_LABEL"></label>
                        <!-- input -->
                        <ptg-ui-input class="w-100" formControlName='confirmPassword' id='inputconfirmPass'
                            type="password" className="form-control bg_0"
                            [placeholder]="resources.CONFIRM_PASSWORD_PLACEHOLDERE">
                        </ptg-ui-input>
                    </div>
                    <div class="row">
                        <div class="col-7">
                            <!-- button -->
                            <ptg-ui-button class="" type="submit" btnStyleType="primary" [isDisable]='!resetForm.valid'>
                                {{resources.RESET_PASSWORD_TEXT}}
                            </ptg-ui-button>
                        </div>
                        <div class="col-5">
                            <!-- placeholder for cancel button -->
                            <ng-content></ng-content>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- reset wrapper End -->
