// apps/web-comp-react/src/app/pages/Radio.js
import React from 'react';
import { PtgRadiobuton } from '@ptg-ui/web-components-react';
function Radio() {
  return (
    <div className="radio container">
      <h3 className="title-align">Radio Buttons</h3>
      <div className="row">
        <PtgRadiobuton
          type="radio"
          id="mybtn"
          name="radios"
          value="A"
          sender="Option 1"
        ></PtgRadiobuton>
        <PtgRadiobuton
          type="radio"
          id="mybtn1"
          name="radios"
          value="B"
          sender="Option 2"
        ></PtgRadiobuton>
      </div>
    </div>
  );
}

export default Radio;

// apps/ptg-ui-web-comp-angular/src/app/componets/radio/radio.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'ptg-ui-radio',
  templateUrl: './radio.component.html',
  styleUrls: ['./radio.component.css']
})
export class RadioComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="radio container">
    <h3 class="title-align">Radio Buttons</h3>
    <div class="row">
      <ptg-radiobuton
        type="radio"
        id="mybtn"
        name="radios"
        value="A"
        sender="Option 1"
      ></ptg-radiobuton>
      <ptg-radiobuton
        type="radio"
        id="mybtn1"
        name="radios"
        value="B"
        sender="Option 2"
      ></ptg-radiobuton>
    </div>
  </div>
