// apps/ptg-ui-web-comp-angular/src/app/componets/calender/calender.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'ptg-ui-calender',
  templateUrl: './calender.component.html',
  styleUrls: ['./calender.component.css'],
})
export class CalenderComponent implements OnInit {
  getCalendarValue(val: any) {
    console.log('val', val);
  }
  date = new Date('10/09/2021');
  ngOnInit(): void {}
}

<div class="calender container">
    <h3 class="title-align">Calender</h3>
    <div class="row">
      <ptg-calender [startDate]="date" ></ptg-calender>
    </div>
  </div>

// apps/ptg-ui-web-comp-react/src/app/pages/calender.tsx
import React from 'react';
import { PtgCalender } from '@ptg-ui/ptg-ui-web-components-react';

function Calender() {
  const [date, setDate] = React.useState(new Date('10/07/2021'));
  const getCalendarValue = (val: any) => {
    console.log('val', val);
  };
  return (
    <div className="calender container">
      <h3 className="title-align">Calender</h3>
      <div className="row">
        <PtgCalender startDate={date} callback={getCalendarValue}></PtgCalender>
      </div>
    </div>
  );
}

export default Calender;
