// apps/web-comp-react/src/app/pages/Buttons.js
import { PtgButton } from '@ptg-ui/web-components-react';

function Buttons() {
  return (
    <div className="buttons container">
      <h3 className="title-align">Buttons</h3>
      <div className="rowList">
        <PtgButton text="Primary" appearance="primary"></PtgButton>
        <PtgButton text="Success" appearance="success"></PtgButton>
        <PtgButton text="Secondary" appearance="secondary"></PtgButton>
        <PtgButton text="Danger" appearance="danger"></PtgButton>
        <PtgButton text="Warning" appearance="warning"></PtgButton>
        <PtgButton text="Info" appearance="info"></PtgButton>
        <PtgButton text="Light" appearance="light"></PtgButton>
        <PtgButton text="Dark" appearance="dark"></PtgButton>
      </div>
    </div>
  );
}

export default Buttons;

// apps/ptg-ui-web-comp-angular/src/app/componets/buttons/buttons.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'ptg-ui-buttons',
  templateUrl: './buttons.component.html',
  styleUrls: ['./buttons.component.css']
})
export class ButtonsComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="buttons container">
    <h3 class="title-align">Buttons</h3>
    <div class="rowList">
      <ptg-button text="Primary" appearance="primary"></ptg-button>
      <ptg-button text="Success" appearance="success" ></ptg-button>
      <ptg-button text="Secondary" appearance="secondary"></ptg-button>
      <ptg-button text="Danger" appearance="danger"></ptg-button>
      <ptg-button text="Warning" appearance="warning"></ptg-button>
      <ptg-button text="Info" appearance="info"></ptg-button>
      <ptg-button text="Light" appearance="light"></ptg-button>
      <ptg-button text="Dark" appearance="dark"></ptg-button>
    </div>
  </div>
