// apps/ptg-angular-app/src/app/common/footer/footer.component.ts
import { Component } from '@angular/core';
import { resources } from "../../../resource/resource";
/**
 * @since March 2022
 * @author Bhanu Prakash Sharma
 * @Component ptg-ui-footer;
 * @description This component for footer
**/

@Component({
  selector: 'ptg-ui-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss']
})
export class FooterComponent  {
  resources=resources
}

<footer class="d-flex justify-content-center align-items-center">
    <p class="m-0" [innerHTML]="resources.FOOTER_TEXT"></p>
</footer>

// apps/ptg-react-animations/src/app/common/footer/Footer.tsx
/**
 * @since March 2022
 * @author Ahilyabai Netaji Pawar
 * @desc Footer Component
 * 
*/
import './Footer.scss';
import { useTranslation } from 'react-i18next';
export interface FooterProps {}

// eslint-disable-next-line no-empty-pattern
export function Footer({}: FooterProps) {
  const { t } = useTranslation();
  return (
    <footer className="d-flex justify-content-center align-items-center fixed-bottom">
      <p className="m-0">
        {t('FOOTER_TEXT')}
      </p>
    </footer>
  );
}
export default Footer;
