// apps/ptg-react-app/src/app/examples/auth/forgotpassword/ForgotPassword.tsx
/* eslint-disable jsx-a11y/anchor-is-valid */
/**
 * @since March 2022
 * @author Anmol Mathur
 * @Updatedby Ankit Patidar
 * @Updatedby Harsha Zalawa
 * @desc Forgot Password Component
 *
 */
import { useEffect, useState } from 'react';
import './ForgotPassword.scss';
import { useTranslation } from 'react-i18next';
import { PtgUiButton, PtgUiInput, PtgUiAlert } from '@ptg-ui/react';
import { Modal } from 'react-bootstrap';
import { authClass } from '../services/auth.service';
import { useNavigate } from 'react-router-dom';

export default function ForgotPassword() {
  const { t } = useTranslation();
  const intialState = {
    show: false,
    email: '',
    btnDisable: false,
    showMessage: { show: false, type: '', message: '' },
  };
  const [values, setValues] = useState(intialState);
  const [formErr, setFormErr] = useState({
    email: false,
    password: false,
  });

  //common function to set specific state variable
  const setState: any = (field: string, value: any) => {
    setValues((preState: any) => {
      return {
        ...preState,
        [field]: value,
      };
    });
  };

  const setErrState: any = (field: string, value: any) => {
    setFormErr((preState: any) => {
      return {
        ...preState,
        [field]: value,
      };
    });
  };

  const handleClose = () => setState('show', false);
  const handleShow = () => {
    setValues(intialState);
    setState('show', true);
  };

  //validate email and password
  const validate = (fieldName: string, value: any) => {
    let disabled = false;
    let formErr = false;
    switch (fieldName) {
      case 'email':
        const regexEmail = /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/i;
        if (value === '' || value ? true : false !== regexEmail.test(value)) {
          disabled = true;
          if (!regexEmail.test(value)) {
            formErr = true;
          }
        }
        break;
    }

    setState('disable', disabled);
    setErrState(fieldName, formErr);
  };

  //generic function for all input field
  const handleChange: any = (e: any) => {
    const { name, value } = e.target;
    validate(name, value);
    setValues((preState: any) => {
      return {
        ...preState,
        [name]: value,
      };
    });
  };
  //validate on focus out or blur input
  const handleBlur: any = (e: any) => {
    const { name } = e.target;
    setFormErr((preState: any) => {
      return {
        ...preState,
        [name]: true,
      };
    });
  };

  useEffect(() => {
    let btn = true;
    if (formErr.email == false && values.email !== '') btn = false;
    setState('btnDisable', btn);
  }, [values.email]);

  return (
    <div>
      <a
        className="forgot-password float-end"
        onClick={handleShow}
        data-testid="linkForgotPassword"
      >
        Forgot Password?
      </a>
      <Modal show={values.show}>
        {values.showMessage.show && (
          <PtgUiAlert
            type={values?.showMessage?.type}
            message={values?.showMessage?.message}
          />
        )}
        <div className="forgot-wrapper container-fluid p-0 d-flex justify-content-center align-items-center">
          <div className="forgot-container">
            <div className="forgot-form-wrapper">
              <div className="form-group">
                <div className="text-center mb-3">
                  <h3>{t('FORGOT_PASSWORD')}</h3>
                </div>
              </div>
              <div className="forgot-form">
                <div className="form-group required mb-4">
                  <label htmlFor="inputEmail">{t('LABEL_EMAIL')}</label>
                  <PtgUiInput
                    type="email"
                    className={`w-100 form-control bg_0 ${
                      formErr.email === true ? 'border-danger' : ''
                    }`}
                    name="email"
                    data-testid="email"
                    placeholder={t('INPUT_PLACEHOLDER_EMAIL')}
                    onChange={handleChange}
                    value={values.email}
                    onBlur={values.email === '' ? handleBlur : null}
                  />
                </div>
                <div className="row">
                  <div className="col-9 col-lg-8 col-md-8 col-sm-9 col-xs-9">
                    <PtgUiButton
                      type="submit"
                      variant="primary"
                      data-testid="handleSubmit"
                      disabled={values.btnDisable}
                    >
                      {t('FORGOT_PASSWORD')}
                    </PtgUiButton>
                  </div>
                  <div className="col-3 col-lg-4 col-md-4 col-sm-3 col-xs-3 text-md-end">
                    <PtgUiButton
                      type="submit"
                      variant="secondary"
                      data-testid="handleClose"
                      onClick={handleClose}
                    >
                      {t('CANCEL')}
                    </PtgUiButton>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </Modal>
    </div>
  );
}

// apps/ptg-angular-app/src/app/auth/forgotpassword/forgotpassword.component.ts
/* eslint-disable @nrwl/nx/enforce-module-boundaries */

/**
 * @since March 2022
 * @author Bhanu Prakash Sharma
 * @Component ptg-ui-forgotpassword;
 * @description This component for forgot password
**/

import { Component, Input, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { BsModalRef } from 'ngx-bootstrap/modal';
import { PTGToastsService } from '@ptg-ui/angular/toasts/services/toasts.service';
import { resources } from "../../../resource/resource";

@Component({
  selector: 'ptg-ui-forgotpassword',
  templateUrl: './forgotpassword.component.html',
  styleUrls: ['./forgotpassword.component.scss'],
})
export class ForgotpasswordComponent implements OnInit {
  @Input() modalRef: BsModalRef |any;
  forgotForm!: FormGroup;
  loading = false;
  errorMessage = null;
  resources = resources

  get f() {
    return this.forgotForm.controls;
  }

  constructor(
    private formBuilder: FormBuilder,
    private toastr: PTGToastsService
  ) {}

  ngOnInit(): void {
    this.forgotForm = this.formBuilder.group({
      email: ['', [Validators.required, Validators.email]],
    });
  }

  /* Method for Forgot Password button*/
  onForgotSubmit() {
    this.toastr.showSuccess('', '');
    this.modalRef?.hide();
    this.forgotForm.reset();
  }

  /* Method for Close Alert*/
  // closeAlert(event: any) {}
}

<!-- Loading -->
<ptg-ui-loading [loading]="loading"></ptg-ui-loading>
<!-- Forgot wrapper Start -->
<div class="forgot-wrapper container-fluid p-0 d-flex justify-content-center align-items-center">
    <div class="forgot-container">
        <div class="forgot-form-wrapper">
            <div class="form-group">
                <!-- alert -->
                <!-- <ptg-ui-alert *ngIf="errorMessage" [type]="'danger'" [message]="errorMessage" [isDismissible]='true'
                    (closeAlert)="closeAlert($event)">
                </ptg-ui-alert> -->
            </div>
            <div class="form-group">
                <div class="text-center mb-3">
                    <h3 [innerHTML]="resources.FORGOT_PASSWORD"></h3>
                </div>
            </div>
            <form class="form-forgot" [formGroup]="forgotForm" (ngSubmit)="onForgotSubmit()">
                <div class="forgot-form">
                    <div class="form-group required mb-4">
                        <label for="inputEmail" [innerHTML]="resources.LABEL_EMAIL"></label>
                        <!-- input -->
                        <ptg-ui-input class="w-100" formControlName='email' id='inputEmail' type="text"
                            className="form-control bg_0" [placeholder]="resources.INPUT_PLACEHOLDER_EMAIL">
                        </ptg-ui-input>
                    </div>
                    <div class="row">
                        <div class="col-8">
                            <!-- button -->
                            <ptg-ui-button class="" type="submit" btnStyleType="primary"
                                [isDisable]='!forgotForm.valid'>
                                {{resources.FORGOT_PASSWORD}}
                            </ptg-ui-button>
                        </div>
                        <div class="col-4">
                            <!-- placeholder for cancel button -->
                            <ng-content></ng-content>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- Forgot wrapper End -->
