// apps/ptg-angular-app/src/app/common/userprofile/userprofile.component.ts
/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable @angular-eslint/no-empty-lifecycle-method */
/* eslint-disable @typescript-eslint/no-empty-function */

/**
 * @since March 2022
 * @author Bhanu Prakash Sharma
 * @Component ptg-ui-userprofile;
 * @description This component for userprofile
**/


import { Component, OnInit, TemplateRef } from '@angular/core';
import { BsModalService, BsModalRef } from 'ngx-bootstrap/modal';
import { AuthService } from '../../auth/services/auth.service'
import { resources } from "../../../resource/resource";
@Component({
  selector: 'ptg-ui-userprofile',
  templateUrl: './userprofile.component.html',
  styleUrls: ['./userprofile.component.scss']
})
export class UserprofileComponent implements OnInit {

  constructor(private authService: AuthService, private modalService: BsModalService) { }

  modalRef?: BsModalRef;
  showProfileIcon = false;
  user:any = {};
  shortName:any = '';
  resources=resources
  userName: any = '';

  ngOnInit(): void {
    this.user = JSON.parse(this.authService.getToken())?.user;
    this.userName = this.user?.username;
    const matches = this.user?.username.match(/\b(\w)/g);
    this.shortName = matches?.join('');
  }

  // Method for Show/Hide User Profile
  toggleUserProfileDiv(){
    this.showProfileIcon = !this.showProfileIcon
  }

   // Method for show reset password modal
  passwordReset(template: TemplateRef<any>){
    this.modalRef = this.modalService.show(template);
  }

   // Method for close modal
  isClosemodal(){
    this.modalRef?.hide();
  }

   // Method for logout 
  logout(){
    this.authService.removeToken();
    sessionStorage.clear();
    window.location.reload();
  }
}

<!-- User profile wrapper start -->
<div class="user-wrapper">
  <span class="profile-icon text-white" (click)="toggleUserProfileDiv()">{{shortName}}</span>
  <div [hidden]="!showProfileIcon" class="user-container">
    <div class="triangle-up"></div>
    <div class="list-group">
      <a class="list-group-item list-group-item-action bg-info text-white border-top-0">{{userName}}</a>
      <!-- <a (click)="passwordReset(reset)" class="list-group-item list-group-item-action">Reset Password</a> -->
      <a (click)="logout()" class="list-group-item list-group-item-action">{{resources.LOGOUT}}</a>
    </div>
  </div>
</div>
<!-- User profile wrapper end -->

<!-- Dialog for resetpassword -->
<ng-template #reset let-modal>
  <div class="modal-body app-orders p-0">
    <ptg-ui-reset [modalRef]="modalRef">
      <ptg-ui-button (click)="isClosemodal()" class="" btnStyleType="secondary"> {{resources.CANCEL}} </ptg-ui-button>
    </ptg-ui-reset>
  </div>
</ng-template>

// apps/ptg-react-app/src/app/common/userprofile/UserProfile.tsx
/**
 * @since March 2022
 * @author Sunil Bhawsar
 * @desc User profile component
 *
 */
import { authClass } from '../../auth/services/auth.service';
import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Modal } from 'react-bootstrap';
import { useNavigate } from 'react-router-dom';
import Reset from '../reset/Reset';
import './UserProfile.scss';
import './UserProfile.scss';

export default function UserProfile() {
  const { t } = useTranslation();
  const [toggle, setToggle] = useState(false);
  interface LoggedInUser {
    username?: any;
    shortname?: any;
  }
  const [userData, setUserData] = useState<LoggedInUser>({});
  const navigate = useNavigate();

  const handleLogout = () => {
    authClass.removeToken();
    sessionStorage.clear();
    navigate('/login');
  };

  {
    /*--Start set logged in user data--*/
  }
  const getUserData = JSON.parse(authClass.getToken());
  // if (getUserData === null) {
  //   handleLogout();
  // } else {
  //   useEffect(() => {
  //     getUserData.user.shortname = getUserData.user.username
  //       ?.match(/\b(\w)/g)
  //       ?.join('');
  //     setUserData(getUserData.user);
  //   }, []);
  // }
  useEffect(() => {
    if (getUserData === null) {
      handleLogout();
    } else {
      if(getUserData.user) {
        getUserData.user.shortname = getUserData?.user?.username
        ?.match(/\b(\w)/g)
        ?.join('');
      setUserData(getUserData.user);
      }
      
    }
  }, []);

  {
    /*--End set logged in user data--*/
  }

  return (
    <div className="user-wrapper mt-1">
      {/*--Display user short name--*/}
      <span
        className="profile-icon text-white"
        onClick={() => setToggle(!toggle)}
        data-testid="profileIcon"
      >
        {userData.shortname}
      </span>
      {toggle && (
        <div className="user-container">
          <div className="triangle-up"></div>
          <div className="list-group">
             {/*--Display user username--*/}
            <a className="list-group-item list-group-item-action bg-info text-white border-top-0">
              {userData.username}
            </a>
            {/* <a className="list-group-item list-group-item-action">
              {/* <Reset /> */}
            {/* </a> */}
            <a
              className="list-group-item list-group-item-action"
              onClick={handleLogout}
              data-testid="logout"
            >
              {t('LOGOUT')}
            </a>
          </div>
        </div>
      )}
    </div>
  );
}
// function id(id: any): any {
//   throw new Error('Function not implemented.');
// }
