// apps/ptg-react-app/src/app/examples/web-accessibility/web-accessibility.tsx
/**
 * @since April 2022
 * @author Ahilyabai Netaji Pawar
 * @updatedBy Harsha zalawa
 * @desc Web-accessibility Example
 */

/* eslint-disable jsx-a11y/no-access-key */
import './web-accessibility.scss';
import React, { useEffect, useRef, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { CITY_LIST, GENDER_LIST } from '../../mock/mocks';
import {
  PtgUiButton,
  PtgUiInput,
  PtgUiSelect,
  PtgUiCheckbox,
  PtgUiRadio,
  PtgUiDatePicker,
} from '@ptg-ui/react';
// eslint-disable-next-line @nrwl/nx/enforce-module-boundaries
import { authClass } from '@ptg-react-app/auth/services/auth.service';
import { resources } from '../../resource/resource';
import { useTranslation } from 'react-i18next';
/* eslint-disable-next-line */
export interface WebAccessibilityProps {}
export function WebAccessibility(props: WebAccessibilityProps) {
   const { t } = useTranslation();
  const startRef: any = useRef();

  const [user, setUser]: any = useState({
    isLoading: false,
    username: '',
    email: '',
    gender: 'male',
    city: '',
    password: '',
    selectedCheck: '',
    error: null,
    disable: true,
  });
  const [formErr, setFormErr] = useState({
    username: false,
    email: false,
    gender: false,
    city: false,
    password: false,
  });
  const setState: any = (field: string, value: any) => {
    setUser((preState: any) => {
      return {
        ...preState,
        [field]: value,
      };
    });
  };
  const setErrState: any = (field: string, value: any) => {
    setFormErr((preState: any) => {
      return {
        ...preState,
        [field]: value,
      };
    });
  };
  const handleChange: any = (e: any) => {
    const { name, value } = e.target;
    console.log('name' + name);
    console.log('value' + value);
    validate(name, value);
    setUser((preState: any) => {
      return {
        ...preState,
        [name]: value,
      };
    });
  };
  const [date, setDate] = useState(null);
  const dateChange = (date: any) => {
    setDate(date);
  };
  const [selectedCheck, setSelectedCheck] = useState<boolean>(false);
  const checkHandler = (event: React.ChangeEvent<HTMLInputElement>) => {
    setSelectedCheck(event.target.checked);
  };
  const isDisabled: any = () => {
    setState(
      'disable',
      !(
        user.email.length > 0 &&
        user.password.length > 0 &&
        !formErr.email &&
        !formErr.password &&
        user.username.length > 0 &&
        user.city.length > 0 &&
        user.gender.length > 0 &&
        selectedCheck &&
        date
      )
    );
  };
  const validate = (fieldName: string, value: any) => {
    let disabled = false;
    let formErr = false;
    switch (fieldName) {
      case 'username':
        if (value !== '') {
          disabled = true;
        }
        break;
      case 'email':
        // eslint-disable-next-line no-case-declarations
        const regexEmail = /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/i;
        if (value === '' || value ? true : false !== regexEmail.test(value)) {
          disabled = true;
          if (!regexEmail.test(value)) {
            formErr = true;
          }
        }
        break;
      case 'city':
        if (value !== '') {
          disabled = true;
        }
        break;
      case 'gender':
        if (value !== '') {
          disabled = true;
        }
        break;
      case 'password':
        if (value !== '') {
          disabled = true;
        }
        break;
      default: {
        disabled = true;
      }
    }
    setErrState(fieldName, formErr);
  };
  useEffect(() => {
    isDisabled();
  }, [
    user.username,
    user.email,
    date,
    user.city,
    user.gender,
    user.password,
    selectedCheck,
  ]);

  //validate on focus out or blur input
  const handleBlur: any = (e: any) => {
    const { name } = e.target;
    setFormErr((preState: any) => {
      return {
        ...preState,
        [name]: true,
      };
    });
  };

  const navigate = useNavigate();
  const handleRegister = (event: any) => {
    event.preventDefault();
    setState('error', null);
    setState('isLoading', true);
    authClass
      .signUp({
        username: user.value,
        email: user.email,
        DOB: user.date,
        city: user.city,
        gender: user.gender,
        password: user.password,
      })
      .then((response: any) => {
        if (response) {
          setState('isLoading', false);
          localStorage.setItem('token', response);
          navigate('/login');
        }
      })
      .catch((error: any) => {
        console.log(error);
      });
  };
  return (
    <div className=" signup-wrappper container-fluid p-0 d-flex justify-content-center align-items-center">
      <div className="signup-container">
        <div className="signup-form-wrapperr">
          <div className="form-group">
            <div className="text-center mb-3">
              <h1>{t('WEB_ACCESSIBILITY_TEXT')}</h1>
            </div>
          </div>
          <div className="row access-wrapper">
            <div className="col-12">
              <form className="form-login">
                <div className="login-form w-75 m-auto">
                  <div className="form-container">
                    <div className="row">
                      <div className="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                        <div className="form-group required mb-2">
                          <label
                            htmlFor="inputUsername"
                            tabIndex={0}
                            aria-label="User Name"
                          >
                            {t('USER_NAME')}
                          </label>
                          <PtgUiInput
                            type="text"
                            name="username"
                            id="inputUsername"
                            data-testid="username"
                            placeholder={t('USER_NAME_PLACEHOLDER')}
                            // accessKey="u"
                            value={user.username}
                            onChange={handleChange}
                            className={`w-100 form-control bg_0 ${
                              formErr.username ? 'border-danger' : ''
                            }`}
                            onBlur={user.username === '' ? handleBlur : null}
                          />
                        </div>
                      </div>
                      <div className="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                        <div className="form-group required mb-2">
                          <label
                            htmlFor="inputEmail"
                            tabIndex={0}
                            aria-label="Email"
                          >
                            {t('LABEL_EMAIL')}
                          </label>
                          <PtgUiInput
                            type="email"
                            name="email"
                            id="inputEmail"
                            data-testid="email"
                            placeholder={t('INPUT_PLACEHOLDER_EMAIL')}
                            //accessKey="m"
                            value={user.email}
                            onChange={handleChange}
                            className={`w-100 form-control bg_0 ${
                              formErr.email ? 'border-danger' : ''
                            }`}
                            onBlur={user.email === '' ? handleBlur : null}
                          />
                        </div>
                      </div>
                      <div className="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                        <div className="form-group required mb-2">
                          <label
                            htmlFor="inputDOB"
                            tabIndex={0}
                            aria-label="DOB"
                            id="enterDOB"
                          >
                            {t('DOB')}
                          </label>
                          <PtgUiDatePicker
                            variant="inline"
                            className="date-picker mt-1 w-100"
                            format="MM/dd/yyyy"
                            id="inputDOB"
                            data-testid="inputDOB"
                            placeholder={t('DATE_PLACEHOLDER')}
                            inputVariant="outlined"
                            value={date}
                            onChange={dateChange}
                            //accessKey="c"
                            ariaLabel="date"
                            disableRipple={true}
                            disableTouchRipple={true}
                          />
                        </div>
                      </div>
                    </div>
                    <div className="row">
                      <div className="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <div className="form-group required mb-2">
                          <label
                            htmlFor="inputCity"
                            tabIndex={0}
                            aria-label="city"
                          >
                            {t('CITY')}
                          </label>
                          <PtgUiSelect
                            name="city"
                            list={CITY_LIST}
                            id="inputCity"
                            data-testid="city"
                            // className={`sel-placeholder w-100`}
                            className={`sel-placeholder w-100 ${
                              formErr.city ? 'border-danger' : ''
                            }`}
                            onChange={handleChange}
                            value={user.city}
                            aria-label="given-name"
                            onBlur={user.city === '' ? handleBlur : null}
                          />
                        </div>
                      </div>
                      <div className="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <div className="form-group required mb-2">
                          <fieldset>
                            <legend className="gender-align">
                              <label tabIndex={0} aria-label="Gender">
                                {t('GENDER')}
                              </label>
                            </legend>

                            <div className="d-flex">
                              <PtgUiRadio
                                name="gender"
                                htmlFor="radioinputForGender"
                                id="radioinputForGender"
                                list={GENDER_LIST}
                                // accessKey="g"
                                onChange={handleChange}
                                value={user.gender}
                              />
                            </div>
                          </fieldset>
                        </div>
                      </div>
                    </div>
                    <div className="row"></div>
                    <div className="row">
                      <div className="col-12">
                        <div className="form-group required mb-2">
                          <label
                            htmlFor="inputPassword"
                            tabIndex={0}
                            aria-label="Password"
                          >
                            {t('LABEL_PASSWORD')}
                          </label>
                          <PtgUiInput
                            type="password"
                            className={`w-100 form-control bg_0`}
                            value={user.password}
                            onChange={handleChange}
                            name="password"
                            id="inputPassword"
                            data-testid="password"
                            placeholder={t('ENTER_PASSWORD_PLACEHOLDER')}
                            //accessKey="p"
                          />
                        </div>
                      </div>
                    </div>
                    <div className="row">
                      <div className="col-12">
                        <div className="form-group required mb-2">
                          <PtgUiCheckbox
                            label={t('CONFIRM_LABEL')}
                            htmlFor="confirm"
                            id="confirm"
                            name="confirm-registration"
                            data-testid="confirm-registration"
                            checked={selectedCheck}
                            onChange={checkHandler}
                            className={`form-check-input `}
                            //accessKey="i"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                  <PtgUiButton
                    className="w-100"
                    type="button"
                    onClick={handleRegister}
                    disabled={user.disable}
                    //accessKey="s"
                    aria-label="submit"
                    data-testid="register"
                  >
                    {t('SUBMIT')}
                  </PtgUiButton>
                </div>
                <div className="row mt-5">
                  <div className="col-md-12">
                    <h2>{t('ACHIEVED_HEADING')}</h2>
                        <ol>
                          <li>{t('ACHIEVED_PNT_ONE')}</li>
                          <li>{t('ACHIEVED_PNT_TWO')}</li>
                          <li>{t('ACHIEVED_PNT_THREE')}</li>
                          <li>{t('ACHIEVED_PNT_FOUR')}</li>
                          <li>{t('ACHIEVED_PNT_FIVE')}</li>
                        </ol>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
export default WebAccessibility;

// apps/ptg-angular-app/src/app/dashboard/webaccessibility/webaccessibility.component.ts
/* eslint-disable no-useless-escape */
/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable @nrwl/nx/enforce-module-boundaries */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @angular-eslint/no-empty-lifecycle-method */
/* eslint-disable @typescript-eslint/no-empty-function */

/**
 * @since April 2022
 * @author Bhanu Prakash Sharma
 * @Component ptg-ui-webaccessibility;
 * @description This component for web accessibility example
 * @UpdatedBy Aakshay Patidar
 **/

import { AfterViewInit, ChangeDetectorRef, Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { User } from '@ptg-angular-app/auth/models/user.model';
import { CITY_LIST, GENDER_LIST } from '../../mock/mocks';
import { resources } from '../../../resource/resource';
@Component({
  selector: 'ptg-ui-webaccessibility',
  templateUrl: './webaccessibility.component.html',
  styleUrls: ['./webaccessibility.component.scss'],
})
export class WebaccessibilityComponent implements OnInit {
  signupForm!: FormGroup;
  loading = false;
  genderList = GENDER_LIST;
  cityList = CITY_LIST;
  resources = resources;
  serviceData:any

  get f() {
    return this.signupForm.controls;
  }

  constructor(
    private formBuilder: FormBuilder,
    private cdr: ChangeDetectorRef

  ) { }

  ngOnInit(): void {
    this.signupForm = this.formBuilder.group({
      userName: ['', [Validators.required]],
      email: ['', [Validators.required,Validators.email]],
      gender: [null, Validators.required],
      city: [null, Validators.required],
      dob: ['', [Validators.required]],
      password: [null, [Validators.required]],
      confirm: [false, [Validators.requiredTrue]],
    });
    
  }

  // This method for signup submit
  onSignupSubmit() {
    const payload = {
      username: this.signupForm.value.userName,
      email: this.signupForm.value.email,
      gender: this.signupForm.value.gender,
      city: this.signupForm.value.city,
      dob: this.signupForm.value.dob,
      password: this.signupForm.value.password,
    };    
    this.userSignup(payload);
  }

  // This method for signUp api call
  userSignup(payload: User) {
    // this.loading = true;
    alert('userSignedUp');
  }

  // this code is used for only web-accessibility (for custom ng select issue)
  ngAfterViewInit() {
    const x: any = document.getElementsByClassName('ng-input');
    for (let i = 0; i < x.length; i++) {
      this.setAttributes(x[i].children[0], {
        autocomplete: 'given-name',
        'aria-label': 'given-label',
      });
      Object.assign(x[i].children[0], {
        autocomplete: 'given-name',
        'aria-label': 'given-label',
      });
      
    }
   
    this.cdr.detectChanges()
  }

  setAttributes(elements: any, attributes: any) {
    
    Object.keys(attributes).forEach(function (name) {
      elements.setAttribute(name, attributes[name]);
    });
  }
}

<!-- Loading -->
<ptg-ui-loading [loading]="loading"></ptg-ui-loading>

<!-- Signup wrapper Start -->
<div class="signup-wrapper container-fluid p-0 d-flex justify-content-center align-items-center">
    <div class="signup-container">
        <div class="signup-form-wrapper">
            <div class="form-group">
                <div class="text-center mb-3">
                    <h1 [innerHTML]="'WEB_ACCESSIBILITY_TEXT' | translate"></h1>
                </div>
            </div>
            <div class="row access-wrapper">
                <!-- <h2>How to access</h2> -->
                <!-- <div class="col-5 ">
                    <ol>
                        <li><strong>Tab </strong> key for forword control</li>
                        <li><strong>Shift + Tab </strong> key for backword control</li>
                        <li><strong>Alt + u </strong> key for username</li>
                        <li><strong>Alt + m </strong> key for email </li>
                        <li><strong>Alt + c </strong> key for DOB (calendar)</li>
                        <li><strong>Alt + g </strong> key for gender </li>
                        <li><strong>Alt + p </strong> key for password</li>
                        <li><strong>Alt + i </strong> key for checkbox </li>
                        <li><strong>Alt + s </strong> key for submit button</li>
                    </ol>
                </div> -->
                <div class="col-12">
                    <form class="form-login" [formGroup]="signupForm" (ngSubmit)="onSignupSubmit()">
                        <div class="login-form w-75 m-auto">
                            <div class="form-container">
                                <div class="row">
                                    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                                        <div class="form-group required mb-2">
                                            <label tabindex="0" for="user_name" aria-label="User Name"
                                                [innerHTML]="'USER_NAME' | translate"></label>
                                            <!-- input -->
                                            <ptg-ui-input [id]="'user_name'" class="w-100" formControlName='userName'
                                                type="text" className="form-control bg_0"
                                                [placeholder]="'USER_NAME_PLACEHOLDER' | translate"
                                                aria_placeholder="Enter User Name">
                                            </ptg-ui-input>

                                        </div>
                                    </div>
                                    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                                        <div class="form-group required mb-2">
                                            <label tabindex="0" for="inputEmail" aria-label="Email"
                                                [innerHTML]="'LABEL_EMAIL' | translate"></label>
                                            <!-- input -->
                                            <ptg-ui-input class="w-100" formControlName='email' [id]="'inputEmail'"
                                                type="text" className="form-control bg_0"
                                                [placeholder]="'INPUT_PLACEHOLDER_EMAIL' | translate"
                                                aria_placeholder="Enter Email">
                                            </ptg-ui-input>
                                        </div>
                                    </div>
                                    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                                        <div class="form-group required mb-2">
                                            <label tabindex="0" aria-label="DOB" [innerHTML]="'DOB' | translate"></label>
                                            <!-- calendar -->
                                            <ptg-ui-calendar class="w-100" aria-label="enterDOB" [id]="'inputDob'"
                                                formControlName='dob' aria_placeholder="MM-DD-YYYY">
                                            </ptg-ui-calendar>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                        <div class="form-group required mb-2">
                                            <label tabindex="0" aria-label="City" [innerHTML]="'CITY' | translate"></label>
                                            <!-- select -->
                                            <ptg-ui-select formControlName='city' class="w-100" [items]='cityList'
                                                [isMultiple]="false" [closeOnSelect]="true"
                                                [placeholder]="'SELECT_PLACEHOLDER' | translate">
                                            </ptg-ui-select>
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                        <div class="form-group required mb-2">
                                            <!-- <label tabindex="0" [innerHTML]="'GENDER' | translate"></label> -->
                                            <fieldset>
                                                <legend tabindex="0" [innerHTML]="'GENDER' | translate" class="legend-tag">
                                                </legend>
                                                <!-- <label tabindex="0" [innerHTML]="'GENDER' | translate"></label> -->
                                                <ptg-ui-radio formControlName='gender' [items]='genderList'
                                                    [name]="'gender-radio-btn'">
                                                </ptg-ui-radio>
                                            </fieldset>

                                        </div>
                                    </div>
                                </div>
                                <div class="row">

                                </div>
                                <div class="row">
                                    <div class="col-12">
                                        <div class="form-group required mb-2">
                                            <label tabindex="0" for="inputPassword" aria-label="Password"
                                                [innerHTML]="'LABEL_PASSWORD' | translate"></label>
                                            <!-- input -->
                                            <ptg-ui-input class="w-100" [id]="'inputPassword'" type="password"
                                                formControlName="password" className="form-control bg_0"
                                                [placeholder]="'INPUT_PLACEHOLDER_PASSWORD' | translate">
                                            </ptg-ui-input>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-12">
                                        <div class="form-group required mb-2">
                                            <!-- checks -->
                                            <ptg-ui-checks formControlName='confirm'
                                                [label]="'DECLARATION_REGISTRATION_TEXT' | translate">
                                            </ptg-ui-checks>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="new_label text-center mt-3 mb-2">
                                <!-- <label tabindex="0">If you have already account please click on <a class="signup-btn"
                                        [routerLink]="['#']">Login</a>.</label> -->
                            </div>
                            <!-- button -->
                            <ptg-ui-button class="w-100" type="submit" btnStyleType="primary" [isBlock]='true'
                                [isDisable]='!signupForm.valid' aria-label="submit">
                                {{'SUBMIT' | translate}}
                            </ptg-ui-button>
                        </div>
                        <div class="row mt-5">
                            <div class="col-md-12">
                                <!-- <h2 [innerHTML]="'ACHIEVED_IN_WEB_ACCESSIBILITY.HEADING' | translate"></h2>
                                <div *ngFor="let list of resources.ACHIEVED_IN_WEB_ACCESSIBILITY.ACHIEVED_POINTS; let i=index;">
                                    <p><b class="me-1">{{i+1}}.</b>{{list}}</p>
                                </div> -->

                                <h2 [innerHTML]="'ACHIEVED_HEADING' | translate"></h2>
                                <div>
                                    <!-- <p><b class="me-1">1.</b>{{'ACHIEVED_PNT_ONE' |translate}}</p>
                                    <p><b class="me-1">2.</b>{{'ACHIEVED_PNT_TWO' |translate}}</p>
                                    <p><b class="me-1">3.</b>{{'ACHIEVED_PNT_THREE' |translate}}</p>
                                    <p><b class="me-1">4.</b>{{'ACHIEVED_PNT_FOUR' |translate}}</p>
                                    <p><b class="me-1">5.</b>{{'ACHIEVED_PNT_FIVE' |translate}}</p> -->
                                    <ol>
                                        <li>{{'ACHIEVED_PNT_ONE' |translate}}</li>
                                        <li>{{'ACHIEVED_PNT_TWO' |translate}}</li>
                                        <li>{{'ACHIEVED_PNT_THREE' |translate}}</li>
                                        <li>{{'ACHIEVED_PNT_FOUR' |translate}}</li>
                                        <li>{{'ACHIEVED_PNT_FIVE' |translate}}</li>
                                    </ol>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Signup wrapper End -->
